server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      # 连接池配置
      max-active: 20
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      # 连接超时配置
      time-between-eviction-runs-millis: 60000  # 1分钟检查一次
      min-evictable-idle-time-millis: 300000    # 空闲5分钟断开
      # 连接有效性检查
      test-while-idle: true
      validation-query: SELECT 1
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}

  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    database: ${sky.redis.database}


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 1800000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 1800000
    user-token-name: authentication
  alioss:
    endpoint: ${sky.alioss.endpoint}
    bucket-name: ${sky.alioss.bucket-name}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
    notifyUrl: ${sky.wechat.notifyUrl}
    refundNotifyUrl: ${sky.wechat.refundNotifyUrl}
  zego:
    app-id: ${sky.zego.app-id}
    server-secret: ${sky.zego.server-secret}
    token-ttl: ${sky.zego.token-ttl}
  yscloud:
    app-key: ${sky.yscloud.app-key}
    app-secret: ${sky.yscloud.app-secret}
  sms:
    region-id: ${sky.sms.region-id}
    app-key: ${sky.sms.app-key}
    app-secret: ${sky.sms.app-secret}



#ffmpeg:
#  path: C:\Program Files\ffmpeg\ffmpeg-2025-03-03-git-d21ed2298e-full_build\bin\ffmpeg.exe


hls:
  output-dir: D:/liveMedia/hls  # 确保此目录存在且有写入权限
